name: Gerar animação Food Drop

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar Food Drop
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar o repositório
      - uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. Instalar dependências (se precisar)
      - name: Instalar dependências
        run: pip install --upgrade pip

      # 4. Rodar script para gerar animação
      - name: Gerar animação
        run: |
          python home/runner/work/amanda1304/amanda1304/gerar_animacao.py
          mkdir -p dist
          mv animacao.svg dist/food-drop.svg
          ls -l dist

      # 5. Publicar no branch `output`
      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
