- name: Gerar animação
  run: |
    python gerar_animacao.py
    ls -l animacao.svg

- name: Commit animation
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "actions@github.com"
      git add animacao.svg
      git commit -m "atualiza animação do Food Drop" || echo "Nenhuma mudança para commitar"
      git push
  
